### ISSUE TITLE
De novo database matching fails

### ISSUE THREAD

**Issue by GoogleCodeExporter** [compomics/denovogui#12]
```
What steps will reproduce the problem?
1. Database mapping of de novo results
2.
3.

What is the expected output? What do you see instead?
Matches between fasta file and de novo results.  No amino acid sequence longer 
than 3 was found for tag W.

What version of the product are you using? On what operating system?
1.1.12

Please provide any additional information below.

none
```

Original issue reported on code.google.com by `Hadley....@gmail.com` on 11 Feb 2015 at 12:30

**Comment by hbarsnes** [comment]
As we didn't hear back from the user reporting the issue, we assume that either the issues has been solved in a more recent version of DeNovoGUI or that another workaround has been found. If this is not the case, please let us know and we'll reopen the issue.
