### ISSUE TITLE
DeNovoGUI 1.7.0 An error occured: No amino acid found for letter *. when exporting Peptide matches

### ISSUE THREAD

**Issue by doubled1096** [compomics/denovogui#23]
Hi,
DeNovoGUI 1.7.0 Throws "error occured: No amino acid found for letter *." when exporting Peptide matches.  I have never gotten this function to work in any ver. of the SW.

Love all the SW you guys are putting out there for the community.

**Comment by hbarsnes** [comment]
We are working on fixing the export of the peptide matches, but even when fixed it will not work for this specific FASTA file as the protein sequences cannot contain '*'. These usually represent stop codons, and as we expect amino acids only in the sequences, our parsing of this protein sequence will fail. So please alter your FASTA file accordingly. Then it will work as soon as we get the peptide matches export fixed.

**Comment by doubled1096** [comment]
Thanks Harald,
I’ll check but these DBs should not have * in them.
DD

**Comment by hbarsnes** [comment]
The bug in the peptide matches export was fixed in DeNovoGUI v1.7.4. I'm therefore closing this issue. If you are still having problems with sequences containing '*', please open a new issue and we'll try to locate the problem.
