### ISSUE TITLE
pNovo+ license expired

### ISSUE THREAD

**Issue by BernhardBlank** [compomics/denovogui#24]
The license of pNovo+ seemingly expired with the new year.
Are you in planning to release an updated version of DenovoGUI with renewed license of pNovo+?

While it was still working I also had some issues with pNovo+ stopping to work during analysis of certain files, where i couldn't really pinpoint to where the error might come from, as it occured just in some files of the same batch. 
I will try to reproduce that once the license is renewed, but anyway I guess in that case it would be better to contact the pNovo+ developers directly.

Other than that I want to thank you for your great work and constant improvements!

**Comment by hbarsnes** [comment]
Hi,

Thanks for telling us about this. We will try to upgrade pNovo+ to a version with a valid license.

As for questions regarding the use of pNovo+ we have to refer to the pNovo+ developers, as we don't have access to the pNovo+ code or algorithm details ourselves.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi again,

Just a quick update. I tried to upgrade to the latest version of pNovo+ but it seems like there are some missing files in their current release, so I cannot even get it to start. I've contacted the pNovo+ developers to see if they can fix the problem.

I will let you know as soon as I hear from them. In the meantime you can always use the three other supported algorithms?

Best regards,
Harald

**Comment by BernhardBlank** [comment]
Hi,

thanks for the quick response and for your efforts! I hope the problem can be simply resolved.
I will stick to the other algorithms in the meantime, however pNovo+ seemed to work really fine, would be neat if it could stay integrated in denovoGUI - but thats more in the hands of their developers i suppose..

Thanks and best regards,
Bernhard

**Comment by caetera** [comment]
Hello,

I would like to ask if there any update on the license issue. As I can see, it still exists (at least in 1.9.9).

Working with pNovo+ i found that at certain type of input it experiences some kind of memory leak or infinite recursion (the software just allocate memory until it reaches the limit of 32bit platform and crashes). For myself I solved it using a small wrapper script, that reads the return code of pNovo and tries to localize the problematic spectrum in divide and conquer way. Might it be something similar to your observations, Bernhard?

**Comment by hbarsnes** [comment]
Hi,

I'm afraid there are no news on this issue. We tried to contact the pNovo+ developers but got no reply. And the online version of pNovo+ does still not work on our end. Do you manage to get the current pNovo+ release to work on your side?

Best regards,
Harald

**Comment by BernhardBlank** [comment]
Hi,

thanks for the update!
Same here, I tried to contact them as well but did not get any reply. Also I cannot get the standalone version to run due to lack of a license key.
@caetera What you describe sounds exactly like what I've experienced! No way to check that out in detail at the moment though.

Regards
Bernhard

**Comment by caetera** [comment]
Hi,

thank you for update. I will try to contact the developers of pNovo to get the license. 

@BernhardBlank , I could easily share the script with you, but for the moment I am afraid it doesn't make any sense. 

Best,
Vladimir

**Comment by hbarsnes** [comment]
Hi all,

pNovo+ should now finally work in DeNovoGUI again! Just update to the new DeNovoGUI (v.1.13.0).

No idea how long the licence will last this time though, so please let us know if it runs out again.

Best regards,
Harald

**Comment by userbz** [comment]
It seems that this stupid issue needs to be reopened in the new year...

**Comment by hbarsnes** [comment]
Hi,

Thanks for letting us know. And yes, it seems like the license only lasts one calendar year...

I will try to get an updated license, but last time I tried I got no reply from the pNovo developers.

Best regards,
Harald

**Comment by userbz** [comment]
I managed to get a newer version of pNovo+ from the authors, which should work for this year... 
Also heard from them that a different version called [open-pnovo](http://pubs.acs.org/doi/abs/10.1021/acs.jproteome.6b00716) is about to be released, but comes with its own GUI.

**Comment by userbz** [comment]
I am sharing the 2017 pNovo package I got from the authors via Box.com
https://ki.box.com/s/c1lxrp5okd2m4zg547qgcshu7p3qzjik

**Comment by hbarsnes** [comment]
Hi,

Getting the software itself is not the limiting factor, it's getting the license key. I've sent the pNovo developers an email requesting a new key. Maybe they are quicker at replying this time.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi all,

I finally got the new license from the pNovo developers and just released a new version of DeNovoGUI where pNovo should be working again.

Best regards,
Harald
