### ISSUE TITLE
PepNovo doesn't apply fixed modifications correctly

### ISSUE THREAD

**Issue by airizzo** [compomics/denovogui#30]
In PepNovo results generated with DeNovo GUI (latest version), fixed modifications are applied like variable modifications and only show up some of the time, despite being specified as fixed. For example, in the results below (from the PepNovo .out file), which was run with parameters specifying the fixed modifications n-terminal dimethylation and carbamidomethylated cysteine, many spectra show up with sequences containing neither. With these specifications, every single result should have the dimethylation and every cysteine should be modified. 

Modifications worked as expected for a Novor analysis run in the same session (same spectra and settings files). I'm wondering if there is a bug in how the GUI passes on modification info to PepNovo.

**Non-application of fixed modifications:**
```
>> 0 9747 File: "D:\Orbitrap data\2015\10-Oct2015\16Oct2015\DvH1-IPTL-18Oto16O-Oct16-6.raw"; SpectrumID: "2878"; scans: "9747" (SQS 0.996)
#Index	RnkScr	PnvScr	N-Gap	C-Gap	[M+H]	Charge	Sequence
0	-1.215	68.328	275.094	0.000	1317.678	2	TSHTCVPLK
1	-1.710	68.424	293.198	0.000	1317.678	2	SSHELNPLK
2	-1.929	71.508	188.052	0.000	1317.678	2	STSHTCVPLK
3	-1.947	75.181	293.198	0.000	1317.678	2	SSHEAGVPLK
4	-2.058	71.230	248.153	0.000	1317.678	2	QSHTCVPLK
5	-2.204	68.000	188.052	0.000	1317.678	2	CVELGDVPLK
6	-2.414	68.999	0.000	0.000	1317.678	2	STSTAELDRPLK
7	-2.420	20.453	345.160	0.000	1314.683	2	VFTLTEQM
8	-2.470	22.932	345.160	0.000	1314.683	2	VFTTLEQM
9	-2.513	74.233	275.094	0.000	1317.678	2	TAELGDVPLK
```
**Inconsistent application of fixed modifications:**
```
>> 0 9750 File: "D:\Orbitrap data\2015\10-Oct2015\16Oct2015\DvH1-IPTL-18Oto16O-Oct16-6.raw"; SpectrumID: "2880"; scans: "9750" (SQS 0.676)
#Index	RnkScr	PnvScr	N-Gap	C-Gap	[M+H]	Charge	Sequence
0	0.249	-21.184	130.600	0.000	1320.584	3	AMAGSFYCQR
1	0.078	-21.314	130.600	0.000	1320.584	3	AMASGFYCQR
2	-0.068	-24.494	130.600	0.000	1320.584	3	AMAGSFYCKR
3	-2.339	23.939	0.000	0.000	1323.580	3	AACTVADATGSGSR
4	-2.356	33.587	0.000	0.000	1323.580	3	Q^+28EEHHATGGSSR
5	-2.510	33.238	0.000	0.000	1323.580	3	Q^+28EEHHATGSGSR
6	-2.543	22.780	0.000	0.000	1323.580	3	N^+28CTVADATGVCK
7	-2.547	17.589	0.000	0.000	1323.580	3	ADVEHHACAASR
8	-2.556	17.626	0.000	0.000	1323.580	3	AVDEHHACAASR
9	-2.595	27.553	0.000	0.000	1323.580	3	Y^+28DVPADACTQR
```

**Comment by airizzo** [comment]
I have a few more insights into this bug.
Here is the PepNovo_PTMs.txt file, which was presumably rewritten by DeNovo GUI:
```
#AA  offset      type    locations  symbol  PTM name
N_TERM	28.0313 OPTIONAL N_TERM ^+28 DIMETHYLATION OF PEPTIDE N-TERM
C	57.021464 FIXED ALL C+57 CARBAMIDOMETHYLATION OF C
M	15.994915 OPTIONAL ALL M+16 OXIDATION OF M
```
The problem here seems to be that the n-term modification here is listed as "OPTIONAL", even though it is specified as fixed in the parameters file. I've attached the parameters file here so you can verify this. [IPTLsettings12-14.zip](https://github.com/compomics/denovogui/files/688356/IPTLsettings12-14.zip)

It looks like rather than passing the fixed modification all the way down, De Novo GUI is randomly applying modification labels at the top level, and possibly not changing masses accordingly. This screen shot displays the results view in the GUI for the first spectrum posted in OP. 
![dvulgh_iptl_ 208da_spectrum2878](https://cloud.githubusercontent.com/assets/22552722/21697755/872d8dbc-d359-11e6-8c60-0fd191cbf066.png)
Although in the PepNovo results file, none of the sequences are listed as having n-terminal dimethylation, according to DeNovo GUI one, but not all of the sequences are. 

Hope there's an easy fix for this.

**Comment by hbarsnes** [comment]
Hi,

I'm afraid the modification support in PepNovo itself is not as complete as one could hope for. Fixed terminal PTMs are sadly not supported. Thus the only way we can support such modifications in DeNovoGUI is to rather add them as variable terminal modifications. Not optimal, but at least it allows you to search for them.

As to the fixed non-terminal modifications, such as carbamidomethylated cysteine, these are not annotated in the PepNovo output file. It is rather assumed that one remembers the search parameters and that carbamidomethylated cysteine is re-added when displaying the data or calculating the peptide mass. This is what we do in DeNovoGUI.

Note also that fixed non-terminal modifications are hidden in DeNovoGUI by default. To show them, go to the View menu and make sure that "Fixed Modifications" is selected. The carbamidomethylated cysteines will then be annotated in the peptide sequences in the table.

I hope this answers your questions?

Best regards,
Harald

**Comment by WaldbauerLab** [comment]
Sorry to hear that. Thanks for the clarification.
