### ISSUE TITLE
DeNovoCLI blast generation

### ISSUE THREAD

**Issue by carlaurangasolis** [compomics/denovogui#31]
Hello,

I am running DeNovoCLI but the blast file is not being generated. It has to be generated via the server becuase they are 2-3 GB files and I don't have the computing power to run it via the GUI. Any thoughts? These are my command line arguments:

java -cp DeNovoGUI-1.15.0.jar com.compomics.denovogui.cmd.IdentificationParametersCLI -out "HCD_par_decoy.par" -db uniprot_all_concatenated_target_decoy.fastaprot_all.fasta -mc 2 -fixed_mods "Carbamidomethylation of C" -variable_mods "Oxidation of M" -pepnovo_hitlist_length 1 -pepnovo_generate_blast 1 -pnovo_activation HCD -pnovo_num_peptides 1 -novor_fragmentation HCD

Thank you very much!

Best wishes from the Mexico science rebellion,

Carla Uranga

**Comment by hbarsnes** [comment]
Hi Carla,

I'm afraid the BLAST feature is not yet supported on the command line. Perhaps you could try doing the de novo search via SearchGUI instead and loading the results in PeptideShaker?

Best regards,
Harald

**Comment by carlaurangasolis** [comment]
Thank you kindly for your response. This helps a lot! I have a random
question for you. Is the NOVOR peptide score basically a -10logP score?

Best wishes,

Carla

**Comment by hbarsnes** [comment]
Hi Carla,

> Is the NOVOR peptide score basically a -10logP score?

I don't know the details of how the Novor score is calculated. I'd recommend checking the Novor paper (https://www.ncbi.nlm.nih.gov/pubmed/?term=26122521) or the Novor wiki (http://wiki.rapidnovor.com/wiki/Main_Page).

Best regards,
Harald
