### ISSUE TITLE
max number of sequences / amino acids in fasta DB

### ISSUE THREAD

**Issue by stijn12** [compomics/denovogui#32]
I got an error while doing the export of Peptide matches using a rather large fasta DB. Regretfully I don't have the log, but the error mentioned that there were too many sequences / amino acids in my database. Is this a memory issue or is there in general a max of sequences / amino acids that can be matched? I used Novor

**Comment by mvaudel** [comment]
Hi and thank you for reporting this issue. This problem has been fixed and we will release new versions very soon.

Best regards,

Marc

**Comment by stijn12** [comment]
tnx!

**Comment by hbarsnes** [comment]
Hi,

We've just released DeNovoGUI v1.15.2 which should fix this problem, if this is not the case please let us know and we'll reopen the issue.

Best regards,
Harald
