### ISSUE TITLE
Problems adding reporter ions to custom modifications

### ISSUE THREAD

**Issue by airizzo** [compomics/denovogui#34]
Hi,
I'm using denovogui 1.15.11 and have created several custom modifications. I've been trying to add reporter ions to these modifications and have had an issue:

- The reporter ion editor doesn't seem to handle masses greater than 200 Da. For one modification, I was able to add multiple reporter ions (all under 200 Da) with no problems. For another modification, I was able to add one reporter ion (mass 156.1) with no problems, but after creating a second one (mass 201.1), the reporter ions field became red and I was unable to save the settings. I tried recreating the reporter ion multiple times and the issue reoccurred. My successful and unsuccessfully saved reporter ions were made in the same way; the only difference I can find is the mass.

Thanks for any assistance you can provide.

A Rizzo

Edit: first issue resolved, second remains.

**Comment by mvaudel** [comment]
Hi,

Thank you for reporting this issue and sorry for the delay of my answer. We are in the middle of major code refactoring that keeps us very busy.

Please note that the de novo sequencing algorithms don't take into account reporter ions and neutral losses so these settings will only impact the display in our user interface. 

I have no problem adding multiple reporter ions with different compositions that make up a mass over 200. Can you send me the atomic composition that is failing?

Thank you,

Marc

**Comment by hbarsnes** [comment]
Issue assumed resolved. If this is not the case, please let us know and we'll reopen the issue.
