### ISSUE TITLE
output file converting?

### ISSUE THREAD

**Issue by HPooky** [compomics/denovogui#35]
Hi,

is it possible to get the output files in one this openacces format?
mzIdentML
mzTab

Or is maybe a converter known for the mgf.out and pnovo.txt files?

Thanks,
HP

**Comment by hbarsnes** [comment]
Hi HP,

> is it possible to get the output files in one this openacces format?

No, I'm afraid not. DeNovoGUI is simply a graphical user interface wrapper on top of the de novo algorithms. It is therefore limited to the output formats supported by the de novo algorithms themselves.

You could consider contacting the developers of the de novo algorithms to see if they have any plans for supporting the standard formats?

But if you have the programming skills (or know somebody who has) it would perhaps be easier to implement your own converter to mzTab?

Best regards,
Harald

**Comment by mvaudel** [comment]
Hi HP,

Note that you can export tab separated files from the export menu, these should be easy to parse in a downstream pipeline. I am not sure whether mzIdentML and mzTab support de novo results. Alternatively, you can load your results in PeptideShaker and export an mzIdentML file from there, but I think only sequences mapping to a protein will be exported.

Hope this helps,

Marc
