### ISSUE TITLE
Novor column empty

### ISSUE THREAD

**Issue by animesh** [compomics/denovogui#36]
No scores show up in Novor column, is it because it needs to be licensed?

**Comment by hbarsnes** [comment]
Hi Animesh,

There is no extra license needed for Novor. Are you sure you selected Novor when performing the de novo sequencing? And that Novor completed without any errors? To retain the Novor log output, please deselect the "Close this dialog when the process is complete" option at the bottom of the progress dialog.

You could also try running Novo in SearchGUI to see if the process completes there?

Best regards,
Harald

**Comment by animesh** [comment]
Dear Harald,

The search completes without issues I think as the respect
 *.novor.csv files are being created for each MGF input. However when i
export the peptide_matched, the column for Novot is empty.

Regards,

Ani


--------------------------"The Answer Lies In The
Genome"--------------------------

[[[ To any NSA and FBI agents reading my email: please consider    ]]]
[[[ whether defending the US Constitution against all enemies,     ]]]
[[[ foreign or domestic, requires you to follow Snowden's example. ]]]
-rms

**Comment by hbarsnes** [comment]
Hi Ani,

And the novor.csv files are not empty? And nothing in the error log?

Are the results there in the table in DeNovoGUI? I.e. are they only missing in the export?

Best regards,
Harald

**Comment by animesh** [comment]
Dear Harald,

The csv files do have results. I have sent the files as a google drive link
to your uib email ID, please check.



Regards,

Ani


--------------------------"The Answer Lies In The
Genome"--------------------------

[[[ To any NSA and FBI agents reading my email: please consider    ]]]
[[[ whether defending the US Constitution against all enemies,     ]]]
[[[ foreign or domestic, requires you to follow Snowden's example. ]]]
-rms

**Comment by hbarsnes** [comment]
Hi Ani,

I did not receive any emails with the links. Perhaps you can try sending them to my gmail address instead?

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi Ani,

The Novor column was missing due to a minor error in our code where we had forgotten to update the code in DeNovoGUI after making a change for parsing the Novor data in PeptideShaker, which both depend on the same backend library. Now corrected. I will release a new version as soon as I've had the time to look into the PepNovo PTM issue.

Best regards,
Harald

**Comment by animesh** [comment]
That is awesome Harald, thanks for the prompt look and correction!

Regards,

Ani


--------------------------"The Answer Lies In The
Genome"--------------------------

[[[ To any NSA and FBI agents reading my email: please consider    ]]]
[[[ whether defending the US Constitution against all enemies,     ]]]
[[[ foreign or domestic, requires you to follow Snowden's example. ]]]
-rms

**Comment by hbarsnes** [comment]
Hi Ani,

I've just released DeNovoGUI v1.15.12 which should solve the problem. If this is not the case, please let me know and I'll reopen the issue.

Best regards,
Harald
