### ISSUE TITLE
Trojan Virus on download?

### ISSUE THREAD

**Issue by charitybechtel** [compomics/denovogui#38]
Hi, i am getting this error when i try to download the program from this link (windows)  http://compomics.github.io/projects/denovogui.html

Gateway Anti-Virus Alert
This request is blocked by the Firewall Gateway Anti-Virus Service. Name: JavaAGNT.AVC (Trojan)

Any ideas or can i get a "clean" link

**Comment by hbarsnes** [comment]
Hi,

This looks like a false positive by the Gateway Anti-Virus. I've just rechecked both the Windows and the Linux/OS X versions of DeNovoGUI (and also manually verified the content) and I don't find any evidence for the reported Trojan virus. Could you check with a different anti-virus software?

Best regards,
Harald
