### ISSUE TITLE
pNovo licence expired

### ISSUE THREAD

**Issue by HPooky** [compomics/denovogui#39]
Hi,

since mid of march I got the message, if I try to run pNovo+:
Sorry, the license has expired. Please visit http://pfind.ict.ac.cn/software/pNovo/ and download the newest version.

Will you get a new license? (I would prefer it, because your interface is a much nicer to view through the data)

Best,
HPooky

**Comment by hbarsnes** [comment]
Hi HPooky,

Thanks for telling us about this. I will contact the pNovo developers and see what can be done. I will keep you posted.

Best regards,
Harald

**Comment by HPooky** [comment]
This would be great. Thanks!

**Comment by hbarsnes** [comment]
Hi HPooky,

Quick update: I got the license key from the pNovo developers. However it seems like they made lots of (largely undocumented) changes compared to the version supported in DeNovoGUI. So much that I have not yet been able to run the new pNovo version without it crashing...

I will try to get the time to look into this in a bit more detail later, but I'm afraid I cannot guarantee that we'll get the new pNovo version to work in DeNovoGUI. At least not without a lot of work.

Best regards,
Harald

**Comment by HPooky** [comment]
Good morning Harald,

that are good news.
Would it be possible to run the pNovo variant from the begin of march with the new key? This version was running good and I could made my analysis with the same programm as my other data.

Thank a lot,
Hpooky

**Comment by hbarsnes** [comment]
Hi HPooky,

I'm afraid the pNovo license does not work that way. It is only used when installing/unzipping the pNovo software, but than later checked when you are running the tool. So there is no way in which I can get the old version to work again as far as I see.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi HPooky,

I had another go at the new pNovo version and got it to work, but at the moment it only works with one thread/process at the time and is therefore relatively slow. But I will look at it again when I get some time and then hopefully release a new version. I'll keep you posted.

Best regards,
Harald

**Comment by hbarsnes** [comment]
Hi HPooky,

I've just released DeNovoGUI v1.16.0 which includes pNovo v3.1.1. The pNovo support is still in beta (which was the case before as well btw), but at least you should now be able to process data again. If this is not the case, please let me know and I'll reopen the issue.

Best regards,
Harald
