### ISSUE TITLE
Contaminant list

### ISSUE THREAD

**Issue by rgohzr** [compomics/denovogui#41]
Hi, is there an option to filter common contaminants from the results on DenovoGUI?

**Comment by hbarsnes** [comment]
Hi,

I'm afraid this is not currently supported. But you can always export the results and perform this kind of filtering outside of DeNovoGUI?

Best regards,
Harald

**Comment by rgohzr** [comment]
Hi Harald, thanks. I'm new to LC-MS/MS proteomics analysis, do you think you'd be able to recommend a downstream workflow/program?

**Comment by hbarsnes** [comment]
Hi again,

If you are new to proteomics data analysis I'd recommend taking a look at our tutorial material: https://compomics.com/bioinformatics-for-proteomics. There is a section on de novo there as well, but it does not really talk all that much about the downstream analysis, so for that you will need to look elsewhere. I don't have any specific suggestions though.

Best regards,
Harald

PS: Given that your original question has been answered I will now close this issue, but please do not hesitate to open a new one if you have other questions about DeNovoGUI.
