### ISSUE TITLE
NullPointerException in DeNovoGUI-1.16.4 IdentificationParametersCLI

### ISSUE THREAD

**Issue by semiller10** [compomics/denovogui#42]
Hello! I encounter an error when attempting to generate a parameters file using DeNovoGUI v1.16.3 and v1.16.4 (Linux), but not v1.16.2.

`>java -cp /path/to/DeNovoGUI-1.16.4/DeNovoGUI-1.16.4.jar com.compomics.denovogui.cmd.IdentificationParametersCLI -out /path/to/params.out -prec_tol 20 -frag_tol 0.5 -fixed_mods "Carbamidomethylation of C" -variable_mods "Oxidation of M" -pepnovo_hitlist_length 20 -novor_fragmentation HCD -novor_mass_analyzer FT`

`java.lang.NullPointerException
        at com.compomics.denovogui.cmd.PathSettingsCLI.setPathSettings(PathSettingsCLI.java:106)
        at com.compomics.denovogui.cmd.PathSettingsCLI.extractAndUpdatePathOptions(PathSettingsCLI.java:240)
        at com.compomics.denovogui.cmd.IdentificationParametersCLI.<init>(IdentificationParametersCLI.java:34)
        at com.compomics.denovogui.cmd.IdentificationParametersCLI.main(IdentificationParametersCLI.java:50)`

Thank you very much,
Sam

**Comment by CarlosHorro** [comment]
Hi,

Thank you very much for the details, we are already working on solving it as soon as possible.

Greetings,
Carlos

**Comment by CarlosHorro** [comment]
Hi again,

We have solved the issue, but, as we cannot temporarily deploy a new version, I've made available to you a DeNovoGUI v1.16.4 with that error fixed, via Dropbox:

Windows: https://www.dropbox.com/s/09xxx9detwquuyp/DeNovoGUI-1.16.4-windows.zip?dl=0

Linux & Mac: https://www.dropbox.com/s/9zb0lkegxif1cmk/DeNovoGUI-1.16.4-mac_and_linux.tar.gz?dl=0

Greetings,
Carlos

**Comment by semiller10** [comment]
Thanks, I'll give it a spin.

**Comment by semiller10** [comment]
Thanks, I'll give it a spin.
