### ISSUE TITLE
can't install denovogui

### ISSUE THREAD

**Issue by jamesraymond1** [compomics/denovogui#46]
I've tried everything. nothing works.
Java is updated
I click on the jar file to open the following screen but when I click on open nothing happens.
the jar file (latest version July 2022) shows up as a Microsoft Internet Explorer program, which is confusing

![denovogui](https://user-images.githubusercontent.com/66270982/183971211-2b9bf6ed-8f9e-4ec6-b0f3-9f6db0550abb.PNG)

**Comment by hbarsnes** [comment]
I assume that you have downloaded the complete DeNovoGUI zip file and not just the jar file (as the screenshot above may seem to indicate)? It is also important that you unzip the zip file before trying to double-click the jar file to start DeNovoGUI.

If the jar file is still not recognized as a Java file you could try installing OpenJDK. You can find the latest version here: https://jdk.java.net/18.

Another option would be to right click the jar file and select the "Open with..." option and there select Java.

**Comment by jamesraymond1** [comment]
I found the problem.  Another program hijacked the jar files on my computer
https://johann.loefflmann.net/en/software/jarfix/index.html
I removed and reinstalled Java and rebooted the computer. Installation now works
