### ISSUE TITLE
Empty output for PepNovo+

### ISSUE THREAD

**Issue by JannikSchneider12** [compomics/denovogui#49]
Hey,

I wanted to run PepNovo+ on my mgf file with ~600k spectra. I used the following parameter file:

[pepnovoplus.txt](https://github.com/compomics/denovogui/files/14551531/pepnovoplus.txt)

The commands that are shown after the file reading are like this:

PepNovo+ command: /home/jannik/Masterthesis/de_novo_peptide_sequencing/de_novo_gui/DeNovoGUI-1.16.8/resources/PepNovo/PepNovo_Linux -file /home/jannik/Masterthesis/de_novo_peptide_sequencing/benchmark_dataset/benchmark_dataset_test_new_1.mgf -model CID_IT_TRYP -PTMs ^+42:C+57:M+16 -fragment_tolerance 0.1 -num_solutions 1 -pm_tolerance 0.05 -use_spectrum_mz -no_quality_filter

...
PepNovo+ command: /home/jannik/Masterthesis/de_novo_peptide_sequencing/de_novo_gui/DeNovoGUI-1.16.8/resources/PepNovo/PepNovo_Linux -file /home/jannik/Masterthesis/de_novo_peptide_sequencing/benchmark_dataset/benchmark_dataset_test_new_20.mgf -model CID_IT_TRYP -PTMs ^+42:C+57:M+16 -fragment_tolerance 0.1 -num_solutions 1 -pm_tolerance 0.05 -use_spectrum_mz -no_quality_filter

The tolerances worked for novor on the same data. However when running PepNovo+, the output file is empty.

Does someone know whats wrong?

Thanks for your time and help

**Comment by hbarsnes** [comment]
Have you tried running the PepNovo+ command lines directly? Are there any errors or messages printed?

**Comment by JannikSchneider12** [comment]
Hey,

I am actually not sure how to do this. If I use one of the shown commands, it says that it doesn't know PepNovo+

**Comment by hbarsnes** [comment]
Try the following.
1) move to the /home/jannik/Masterthesis/de_novo_peptide_sequencing/de_novo_gui/DeNovoGUI-1.16.8/resources/PepNovo folder in your command line interface.
2) try running just PepNovo_Linux.
3) if this works, try running the complete command line: PepNovo_Linux -file /home/jannik/Masterthesis/de_novo_peptide_sequencing/benchmark_dataset/benchmark_dataset_test_new_1.mgf -model CID_IT_TRYP -PTMs ^+42:C+57:M+16 -fragment_tolerance 0.1 -num_solutions 1 -pm_tolerance 0.05 -use_spectrum_mz -no_quality_filter.

**Comment by JannikSchneider12** [comment]
Hey,

Thanks for your answer. It says "PepNovo_Linux: command not found"

**Comment by hbarsnes** [comment]
That is strange. Are you sure that you downloaded the Mac and Linux version of DeNovoGUI and not the Windows version? Please check that you used the correct download link on the main DeNovoGUI page: https://github.com/compomics/denovogui

But if you already downloaded the correct version, please also make sure that you have a file called PepNovo_Linux in the DeNovoGUI-1.16.8/resources/PepNovo folder?

**Comment by JannikSchneider12** [comment]
Hey,

Now it worked, so I had to make the PepNovo_Linux executable. However I am still facing issues with the modifications in my sequences. So I parsed them to match the expected format of PepNovo+, but I am getting this error:

Error parsing peptide string!
EDGGGC+57YDIPNWSALK
     ^
Bad AA label: C+57

Although I thought the format should be right, since the expected mods are listed:

^+42:C+57:M+16

**Comment by hbarsnes** [comment]
I'm not sure what you mean by "parsed them to match the expected format of PepNovo+"? PepNovo+ will take care of adding the modifications that you include in the parameter file, hence there should not be any need for manually parsing or editing the sequences. But maybe I am misunderstanding?

**Comment by JannikSchneider12** [comment]
I meant that I changed the format to the format that PepNovo+ deals with (in the original sequences, there was just the mass inside the sequence string, e.g. I changed +42.011 to ^+42 etc. . But if I get you right, I should just provide the raw sequences ?
And I am also not sure why the sequence parameter of the mgf input is even considered since I thought PepNovo predicts sequences based on my spectra?

Thanks again for your time and help

**Comment by hbarsnes** [comment]
> But if I get you right, I should just provide the raw sequences ?

You should not provide any sequences at all just the spectra (plus the PepNovo+ settings).

> And I am also not sure why the sequence parameter of the mgf input is even considered since I thought PepNovo predicts sequences based on my spectra?

Not sure what you mean by "sequence parameter of the mgf input"? The final part is correct though, i.e. "PepNovo predicts sequences based on my spectra".

**Comment by JannikSchneider12** [comment]
Hey,

I already had sequences in my mgf in the "seq" parameter that were obtained with a DB search. However I thought PepNovo would just ignore those and that this parameter wouldn't matter. But since it did, I removed it and now I could execute it with your provided command directly from the resources. The cmd shows for every spectra e.g. something like this:

>> 0 89368 E_Aurora25_huMu-deepC18_adi_400ng-frac1_A3187-1.8211.8211.2 File:"E_Aurora25_huMu-deepC18_adi_400ng-frac1_A3187-1.raw", NativeID:"controllerType=0 controllerNumber=1 scan=8211" (SQS 0.800)
#Index  RnkScr  PnvScr  N-Gap   C-Gap   [M+H]   Charge  Sequence
0       -0.102  61.669  0.000   147.103 1285.671        2       KEEAEVKEPV

>> 0 810624 E_Aurora25_huMu-deepC18_adi_400ng-frac5_A3188-5.34569.34569.2 File:"E_Aurora25_huMu-deepC18_adi_400ng-frac5_A3188-5.raw", NativeID:"controllerType=0 controllerNumber=1 scan=34569" (SQS 0.487)
#Index  RnkScr  PnvScr  N-Gap   C-Gap   [M+H]   Charge  Sequence
0       5.310   10.982  0.000   0.000   740.363 2       PNDAKPV

However after a while it seems to abort, since I have no output file and the cmd shows just this:

#Processed spectra 617527/619804

**Comment by hbarsnes** [comment]
As far as I remember PepNovo does not provide an output file but simply writes the output directly to the command line window. Hence the results you pasted above are the PepNovo results. In DeNovoGUI we simply pick up this output and send it to a file.

**Comment by JannikSchneider12** [comment]
Okay but this would lead to my original problem that the output file is empty when using it from DeNovoGUI. But I will try to run it from the resources and write the printed lines from the cmd to a txt file

**Comment by hbarsnes** [comment]
> Okay but this would lead to my original problem that the output file is empty when using it from DeNovoGUI.

Unless that issue was related to PepNovo_Linux not being executable? Which you now have fixed?

**Comment by JannikSchneider12** [comment]
Hello,

I could execute it now and save the result file. Thank you very much for your time and help
